name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Flutter (you can switch stable → beta here)
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable   # change to "beta" if you want beta channel
          flutter-version: 3.24.0 # optional, locks version

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Analyze code
      - name: Analyze
        run: flutter analyze

      # Run tests (optional, skip if you don’t have tests)
      - name: Run tests
        run: flutter test || true

      # Build release APK
      - name: Build APK
        run: flutter build apk --release

      # Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
